#!/usr/bin/env node
/**
 * SAP Connection Config Writer
 * Collects SAP connection info and writes .env (+ optionally merges .claude/settings.json).
 * Usage:
 *   node write-config.js
 *   node write-config.js --url http://10.32.21.11:8000 --client 200 --user ITL12 --password "xxx"
 *   node write-config.js --rfc --router /H/210.75.21.252 --sysnr 00
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const root = path.resolve(__dirname, '..');
const envPath = path.join(root, '.env');
const settingsPath = path.join(root, '.claude', 'settings.json');
const userSettingsPath = path.join(
  process.env.USERPROFILE || process.env.HOME || '',
  '.claude', 'settings.json'
);

function parseArgs() {
  const args = process.argv.slice(2);
  const out = {};
  for (let i = 0; i < args.length; i++) {
    const k = args[i];
    const v = args[i + 1];
    if (k === '--url') out.url = v;
    else if (k === '--client') out.client = v;
    else if (k === '--user') out.user = v;
    else if (k === '--password') out.password = v;
    else if (k === '--lang') out.lang = v;
    else if (k === '--sid') out.sid = v;
    else if (k === '--sysnr') out.sysnr = v;
    else if (k === '--router') out.router = v;
    else if (k === '--rfc') out.connectionType = 'rfc';
    else if (k === '--http') out.connectionType = 'http';
  }
  return out;
}

function ask(q, def) {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((resolve) => {
    const prompt = def ? `${q} [${def}]: ` : `${q}: `;
    rl.question(prompt, (ans) => {
      rl.close();
      resolve(ans.trim() || def || '');
    });
  });
}

async function interactive(defaults) {
  console.log('=== SAP Connection Configuration ===\n');
  const url = defaults.url || await ask('SAP URL (e.g. http://10.32.21.11:8000)');
  const client = defaults.client || await ask('Client (e.g. 200)', '200');
  const user = defaults.user || await ask('Username');
  const password = defaults.password || await ask('Password');
  const lang = defaults.lang || await ask('Language', 'ZH');
  const sid = defaults.sid || await ask('System ID / SID (e.g. EE0)');
  const sysnr = defaults.sysnr || await ask('System Number (e.g. 00)', '00');
  const router = defaults.router || await ask('Router string (e.g. /H/210.75.21.252) [optional]');
  const conn = defaults.connectionType || await ask('Connection type (rfc/http)', 'rfc');
  return { url, client, user, password, lang, sid, sysnr, router, connectionType: conn };
}

function generateEnv(cfg) {
  const lines = [
    '# SAP Connection Configuration',
    '# Auto-generated by write-config.js',
    '',
    '# SAP target system URL',
    `SAP_URL=${cfg.url}`,
    '',
    '# SAP Client',
    `SAP_CLIENT=${cfg.client}`,
    '',
    '# Authentication',
    'SAP_AUTH_TYPE=basic',
    `SAP_USERNAME=${cfg.user}`,
    `SAP_PASSWORD=${cfg.password}`,
    '',
    '# Connection type: rfc (for SAP Router) or http',
    `SAP_CONNECTION_TYPE=${cfg.connectionType}`,
    '',
    '# SAP Router String (RFC mode only)',
    `SAP_ROUTER=${cfg.router || ''}`,
    '',
    '# SAP System ID and Number (for reference/transport naming)',
    `SAP_SID=${cfg.sid || ''}`,
    `SAP_SYSNR=${cfg.sysnr || ''}`,
    '',
    '# Debug logging (optional)',
    '# DEBUG_AUTH_LOG=true',
  ];
  return lines.join('\n') + '\n';
}

function mergeSettingsJson(cfg, targetPath) {
  let data = {};
  if (fs.existsSync(targetPath)) {
    try {
      data = JSON.parse(fs.readFileSync(targetPath, 'utf8'));
    } catch (e) {
      console.warn(`[WARN] Failed to parse ${targetPath}, will overwrite.`);
    }
  }
  if (!data.mcpServers) data.mcpServers = {};

  // Prefer RFC launcher if connection type is rfc and NW-RFC-SDK exists
  const sdkHome = path.join(root, 'NW-RFC-SDK', 'nwrfcsdk');
  const isRfc = cfg.connectionType === 'rfc';
  const hasSdk = fs.existsSync(path.join(sdkHome, 'lib', 'sapnwrfc.dll'));

  if (isRfc && hasSdk) {
    data.mcpServers['abap-adt'] = {
      command: 'node',
      args: [path.join(root, 'mcp-launcher.js').replace(/\\/g, '/')],
      disabled: false,
    };
  } else {
    data.mcpServers['ai-abap'] = {
      command: 'node',
      args: ['<ENTRY>'],
      env: {
        SAP_URL: cfg.url,
        SAP_USER: cfg.user,
        SAP_PASSWORD: cfg.password,
        SAP_CLIENT: cfg.client,
        SAP_LANGUAGE: cfg.lang,
        NODE_TLS_REJECT_UNAUTHORIZED: '0',
      },
      disabled: false,
    };
  }

  const dir = path.dirname(targetPath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(targetPath, JSON.stringify(data, null, 2));
  console.log(`[WRITE] ${targetPath}`);
}

async function main() {
  const args = parseArgs();
  const needsInteractive = !args.url || !args.user || !args.password || !args.client;
  const cfg = needsInteractive ? await interactive(args) : args;

  // Write .env
  fs.writeFileSync(envPath, generateEnv(cfg));
  console.log(`[WRITE] ${envPath}`);

  // Merge settings.json (project-level preferred for portability)
  if (fs.existsSync(path.dirname(settingsPath)) || needsInteractive) {
    mergeSettingsJson(cfg, settingsPath);
  }

  console.log('\n[OK] Configuration saved.');
  console.log(`     URL:      ${cfg.url}`);
  console.log(`     Client:   ${cfg.client}`);
  console.log(`     User:     ${cfg.user}`);
  console.log(`     Type:     ${cfg.connectionType}`);
  if (cfg.router) console.log(`     Router:   ${cfg.router}`);
  console.log('\nNext: restart Claude Code or run "node scripts/setup.js" to verify.');
}

main().catch((e) => {
  console.error('[ERR]', e.message);
  process.exit(1);
});
