const fs = require('fs');
const path = require('path');
const base = 'output/ZTEST102/metadata/tables';

// SKA1
fs.writeFileSync(path.join(base, 'SKA1.json'), JSON.stringify({tabname:'SKA1',fields:[
  {FIELDNAME:'MANDT',KEYFLAG:'X',DATATYPE:'CLNT',LENG:3},{FIELDNAME:'KTOPL',KEYFLAG:'X',DATATYPE:'CHAR',LENG:4},
  {FIELDNAME:'SAKNR',KEYFLAG:'X',DATATYPE:'CHAR',LENG:10},{FIELDNAME:'XBILK',DATATYPE:'CHAR',LENG:1},
  {FIELDNAME:'SAKAN',DATATYPE:'CHAR',LENG:10},{FIELDNAME:'BILKT',DATATYPE:'CHAR',LENG:10},
  {FIELDNAME:'ERDAT',DATATYPE:'DATS',LENG:8},{FIELDNAME:'ERNAM',DATATYPE:'CHAR',LENG:12},
  {FIELDNAME:'GVTYP',DATATYPE:'CHAR',LENG:2},{FIELDNAME:'KTOKS',DATATYPE:'CHAR',LENG:4},
  {FIELDNAME:'MUSTR',DATATYPE:'CHAR',LENG:10},{FIELDNAME:'VBUND',DATATYPE:'CHAR',LENG:6},
  {FIELDNAME:'XLOEV',DATATYPE:'CHAR',LENG:1},{FIELDNAME:'XSPEA',DATATYPE:'CHAR',LENG:1},
  {FIELDNAME:'XSPEB',DATATYPE:'CHAR',LENG:1},{FIELDNAME:'XSPEP',DATATYPE:'CHAR',LENG:1},
  {FIELDNAME:'MCOD1',DATATYPE:'CHAR',LENG:25},{FIELDNAME:'FUNC_AREA',DATATYPE:'CHAR',LENG:16},
  {FIELDNAME:'ZFKYH',DATATYPE:'CHAR',LENG:64},{FIELDNAME:'ZYHZH',DATATYPE:'CHAR',LENG:50},
  {FIELDNAME:'ZBUKRS',DATATYPE:'CHAR',LENG:4},{FIELDNAME:'ZZGS',DATATYPE:'CHAR',LENG:4},
  {FIELDNAME:'ZXHRQ',DATATYPE:'DATS',LENG:8}
]}, null, 2));

// SKAT
fs.writeFileSync(path.join(base, 'SKAT.json'), JSON.stringify({tabname:'SKAT',fields:[
  {FIELDNAME:'MANDT',KEYFLAG:'X',DATATYPE:'CLNT',LENG:3},{FIELDNAME:'SPRAS',KEYFLAG:'X',DATATYPE:'LANG',LENG:1},
  {FIELDNAME:'KTOPL',KEYFLAG:'X',DATATYPE:'CHAR',LENG:4},{FIELDNAME:'SAKNR',KEYFLAG:'X',DATATYPE:'CHAR',LENG:10},
  {FIELDNAME:'TXT20',DATATYPE:'CHAR',LENG:20},{FIELDNAME:'TXT50',DATATYPE:'CHAR',LENG:50},
  {FIELDNAME:'MCOD1',DATATYPE:'CHAR',LENG:25}
]}, null, 2));

// ZSAP_BUKRS
fs.writeFileSync(path.join(base, 'ZSAP_BUKRS.json'), JSON.stringify({tabname:'ZSAP_BUKRS',fields:[
  {FIELDNAME:'MANDT',KEYFLAG:'X',DATATYPE:'CLNT',LENG:3},{FIELDNAME:'BUKRS',KEYFLAG:'X',DATATYPE:'CHAR',LENG:4},
  {FIELDNAME:'PRCTR',DATATYPE:'CHAR',LENG:10},{FIELDNAME:'LTEXT',DATATYPE:'CHAR',LENG:40},
  {FIELDNAME:'ZFGS',DATATYPE:'CHAR',LENG:1},{FIELDNAME:'ZZGS',DATATYPE:'CHAR',LENG:4},
  {FIELDNAME:'BUTXT',DATATYPE:'CHAR',LENG:25},{FIELDNAME:'ZSYS',DATATYPE:'CHAR',LENG:1}
]}, null, 2));

// ZSAP_FI179 - output table (critical for code)
const fi179Fields = [
  {FIELDNAME:'MANDT',KEYFLAG:'X',DATATYPE:'CLNT',LENG:3},{FIELDNAME:'FLNUM',KEYFLAG:'X',DATATYPE:'CHAR',LENG:4},
  {FIELDNAME:'RBUKRS',KEYFLAG:'X',DATATYPE:'CHAR',LENG:4},{FIELDNAME:'RLTEXT',KEYFLAG:'X',DATATYPE:'CHAR',LENG:40},
  {FIELDNAME:'RYEAR',KEYFLAG:'X',DATATYPE:'NUMC',LENG:4},{FIELDNAME:'POPER',KEYFLAG:'X',DATATYPE:'NUMC',LENG:3},
  {FIELDNAME:'DOCNR',KEYFLAG:'X',DATATYPE:'CHAR',LENG:10},{FIELDNAME:'DOCLN',KEYFLAG:'X',DATATYPE:'CHAR',LENG:6},
  {FIELDNAME:'BUKRS',DATATYPE:'CHAR',LENG:4},{FIELDNAME:'LTEXT',DATATYPE:'CHAR',LENG:40},
  {FIELDNAME:'BUDAT',DATATYPE:'DATS',LENG:8},{FIELDNAME:'CPUDT',DATATYPE:'DATS',LENG:8},
  {FIELDNAME:'AEDAT',DATATYPE:'DATS',LENG:8},{FIELDNAME:'REVIEWER',DATATYPE:'CHAR',LENG:12},
  {FIELDNAME:'PREPARER',DATATYPE:'CHAR',LENG:12},{FIELDNAME:'POSTER',DATATYPE:'CHAR',LENG:12},
  {FIELDNAME:'APPROVER',DATATYPE:'CHAR',LENG:12},{FIELDNAME:'OPERATOR',DATATYPE:'CHAR',LENG:12},
  {FIELDNAME:'ATTCHNUM',DATATYPE:'INT4',LENG:10},{FIELDNAME:'ADJUST_FLG',DATATYPE:'CHAR',LENG:2},
  {FIELDNAME:'VERNUM',DATATYPE:'CHAR',LENG:5},{FIELDNAME:'BUSTYPE',DATATYPE:'CHAR',LENG:8},
  {FIELDNAME:'XREVERSAL',DATATYPE:'CHAR',LENG:1},{FIELDNAME:'BLART',DATATYPE:'CHAR',LENG:2},
  {FIELDNAME:'ZVOUTY',DATATYPE:'CHAR',LENG:20},{FIELDNAME:'BKTXT',DATATYPE:'CHAR',LENG:25},
  {FIELDNAME:'RACCT',DATATYPE:'CHAR',LENG:10},{FIELDNAME:'RACCT_TXT',DATATYPE:'CHAR',LENG:50},
  {FIELDNAME:'WAERS',DATATYPE:'CUKY',LENG:5},{FIELDNAME:'TSL',DATATYPE:'CURR',LENG:23,DECIMALS:2},
  {FIELDNAME:'HSL_S',DATATYPE:'CURR',LENG:15,DECIMALS:2},{FIELDNAME:'HSL_H',DATATYPE:'CURR',LENG:15,DECIMALS:2},
  {FIELDNAME:'KOSTL',DATATYPE:'CHAR',LENG:10},{FIELDNAME:'KOSTL_TXT',DATATYPE:'CHAR',LENG:40},
  {FIELDNAME:'PRCTR',DATATYPE:'CHAR',LENG:10},{FIELDNAME:'PRCTR_TXT',DATATYPE:'CHAR',LENG:40},
  {FIELDNAME:'SGTXT',DATATYPE:'CHAR',LENG:50},{FIELDNAME:'MATNR',DATATYPE:'CHAR',LENG:18},
  {FIELDNAME:'MAKTX',DATATYPE:'CHAR',LENG:40},{FIELDNAME:'KTOKD',DATATYPE:'CHAR',LENG:4},
  {FIELDNAME:'KTOKD_TXT',DATATYPE:'CHAR',LENG:30},{FIELDNAME:'ZYHZH',DATATYPE:'CHAR',LENG:50},
  {FIELDNAME:'ORGNAME',DATATYPE:'CHAR',LENG:40},{FIELDNAME:'MATKL',DATATYPE:'CHAR',LENG:9},
  {FIELDNAME:'WGBEZ60',DATATYPE:'CHAR',LENG:60},{FIELDNAME:'LIFNR_FI',DATATYPE:'CHAR',LENG:10},
  {FIELDNAME:'NAME1_LIF_FI',DATATYPE:'CHAR',LENG:35},{FIELDNAME:'KUNNR_FI',DATATYPE:'CHAR',LENG:10},
  {FIELDNAME:'NAME1_KUR_FI',DATATYPE:'CHAR',LENG:35},{FIELDNAME:'HKONT_BKN',DATATYPE:'CHAR',LENG:50},
  {FIELDNAME:'HKONT_FDN',DATATYPE:'CHAR',LENG:50},{FIELDNAME:'KUNNR',DATATYPE:'CHAR',LENG:10},
  {FIELDNAME:'NAME1_KUR',DATATYPE:'CHAR',LENG:40},{FIELDNAME:'LIFNR',DATATYPE:'CHAR',LENG:10},
  {FIELDNAME:'NAME1_LIF',DATATYPE:'CHAR',LENG:40},{FIELDNAME:'EXPENSECODE',DATATYPE:'CHAR',LENG:20},
  {FIELDNAME:'EXPENSENAME',DATATYPE:'CHAR',LENG:50},{FIELDNAME:'ANLKL',DATATYPE:'CHAR',LENG:8},
  {FIELDNAME:'NAME1_ANL',DATATYPE:'CHAR',LENG:50},{FIELDNAME:'LIFNR_PA',DATATYPE:'CHAR',LENG:10},
  {FIELDNAME:'NAME1_LIF_PA',DATATYPE:'CHAR',LENG:40},{FIELDNAME:'MEINS',DATATYPE:'UNIT',LENG:3},
  {FIELDNAME:'PRICE',DATATYPE:'CURR',LENG:13,DECIMALS:2},{FIELDNAME:'MENGE',DATATYPE:'QUAN',LENG:13,DECIMALS:3},
  {FIELDNAME:'PAYMETHOD',DATATYPE:'CHAR',LENG:10},{FIELDNAME:'XBLNR',DATATYPE:'CHAR',LENG:16},
  {FIELDNAME:'RAT_TYPE',DATATYPE:'CHAR',LENG:8},{FIELDNAME:'RAT',DATATYPE:'CHAR',LENG:10},
  {FIELDNAME:'BUSNUM',DATATYPE:'CHAR',LENG:64},{FIELDNAME:'ABSLIB',DATATYPE:'CHAR',LENG:20},
  {FIELDNAME:'ZFKYH',DATATYPE:'CHAR',LENG:64},{FIELDNAME:'ACCTDIM',DATATYPE:'CHAR',LENG:10}
];
fs.writeFileSync(path.join(base, 'ZSAP_FI179.json'), JSON.stringify({tabname:'ZSAP_FI179',fields:fi179Fields,fetched_count:72,matched:true}, null, 2));

// ZFI032_DOC
fs.writeFileSync(path.join(base, 'ZFI032_DOC.json'), JSON.stringify({tabname:'ZFI032_DOC',fields:[
  {FIELDNAME:'MANDT',KEYFLAG:'X',DATATYPE:'CLNT',LENG:3},{FIELDNAME:'URID',KEYFLAG:'X',DATATYPE:'CHAR',LENG:32},
  {FIELDNAME:'BANKSERIALNUMBER',KEYFLAG:'X',DATATYPE:'CHAR',LENG:64},{FIELDNAME:'BELNR',KEYFLAG:'X',DATATYPE:'CHAR',LENG:10},
  {FIELDNAME:'GJAHR',KEYFLAG:'X',DATATYPE:'NUMC',LENG:4},{FIELDNAME:'BUKRS',KEYFLAG:'X',DATATYPE:'CHAR',LENG:4},
  {FIELDNAME:'ZCXFLAG',KEYFLAG:'X',DATATYPE:'CHAR',LENG:1},{FIELDNAME:'OURBANKACCOUNTNUMBER',DATATYPE:'CHAR',LENG:64},
  {FIELDNAME:'PROGRAMM',DATATYPE:'CHAR',LENG:40},{FIELDNAME:'ERNAM',DATATYPE:'CHAR',LENG:12},
  {FIELDNAME:'ERDAT',DATATYPE:'DATS',LENG:8},{FIELDNAME:'ERZET',DATATYPE:'TIMS',LENG:6},
  {FIELDNAME:'AENAM',DATATYPE:'CHAR',LENG:12},{FIELDNAME:'AEDAT',DATATYPE:'DATS',LENG:8},
  {FIELDNAME:'AEZET',DATATYPE:'TIMS',LENG:6},{FIELDNAME:'GUID',DATATYPE:'CHAR',LENG:32},
  {FIELDNAME:'AMOUNT',DATATYPE:'CURR',LENG:15,DECIMALS:2},{FIELDNAME:'MULTI_ZSQH',DATATYPE:'CHAR',LENG:120}
]}, null, 2));

// ZSAP_FI054 - placeholder with key fields noted
fs.writeFileSync(path.join(base, 'ZSAP_FI054.json'), JSON.stringify({tabname:'ZSAP_FI054',fetched_count:66,matched:true,keyFields:['MANDT','URID','BANKSERIALNUMBER','BUKRS','BELNR','GJAHR']}, null, 2));

console.log('All JSON metadata saved.');
