// Write hardcoded Z-table metadata to <outdir>/metadata/tables/
// Usage: node scripts/update_z_metadata.js <outdir>
const fs = require('fs');
const path = require('path');

const outdir = process.argv[2];
if (!outdir) {
  console.error('[FATAL] Output directory required. Usage: node scripts/update_z_metadata.js <outdir>');
  process.exit(1);
}
const d = path.join(outdir, 'metadata', 'tables');
fs.mkdirSync(d, { recursive: true });

const tables = {
  'ZSAP_FI179': {
    tabname: 'ZSAP_FI179', source: 'DD03L',
    fields: [
      {FIELDNAME:'MANDT',KEYFLAG:'X',ROLLNAME:'MANDT',DATATYPE:'CLNT',LENG:3},
      {FIELDNAME:'FLNUM',KEYFLAG:'X',ROLLNAME:'ZE_FLNUM',DATATYPE:'CHAR',LENG:4},
      {FIELDNAME:'RBUKRS',KEYFLAG:'X',ROLLNAME:'ZE_RBUKRS',DATATYPE:'CHAR',LENG:4},
      {FIELDNAME:'RLTEXT',KEYFLAG:'X',ROLLNAME:'ZE_RLTEXT',DATATYPE:'CHAR',LENG:40},
      {FIELDNAME:'RYEAR',KEYFLAG:'X',ROLLNAME:'RYEAR',DATATYPE:'NUMC',LENG:4},
      {FIELDNAME:'POPER',KEYFLAG:'X',ROLLNAME:'POPER',DATATYPE:'NUMC',LENG:3},
      {FIELDNAME:'DOCNR',KEYFLAG:'X',ROLLNAME:'DOCNR',DATATYPE:'CHAR',LENG:10},
      {FIELDNAME:'DOCLN',KEYFLAG:'X',ROLLNAME:'DOCLN6',DATATYPE:'CHAR',LENG:6},
      {FIELDNAME:'BUKRS',ROLLNAME:'ZE_FBUKRS',DATATYPE:'CHAR',LENG:4},
      {FIELDNAME:'LTEXT',ROLLNAME:'ZE_FLTEXT',DATATYPE:'CHAR',LENG:40},
      {FIELDNAME:'BUDAT',ROLLNAME:'BUDAT',DATATYPE:'DATS',LENG:8},
      {FIELDNAME:'CPUDT',ROLLNAME:'CPUDT',DATATYPE:'DATS',LENG:8},
      {FIELDNAME:'AEDAT',ROLLNAME:'AEDAT',DATATYPE:'DATS',LENG:8},
      {FIELDNAME:'REVIEWER',ROLLNAME:'ZE_REVIEWER',DATATYPE:'CHAR',LENG:12},
      {FIELDNAME:'PREPARER',ROLLNAME:'ZE_PREPARER',DATATYPE:'CHAR',LENG:12},
      {FIELDNAME:'POSTER',ROLLNAME:'ZE_POSTER',DATATYPE:'CHAR',LENG:12},
      {FIELDNAME:'APPROVER',ROLLNAME:'ZE_APPROVER',DATATYPE:'CHAR',LENG:12},
      {FIELDNAME:'OPERATOR',ROLLNAME:'ZE_OPERATOR',DATATYPE:'CHAR',LENG:12},
      {FIELDNAME:'ATTCHNUM',ROLLNAME:'ZE_ATTCHNUM',DATATYPE:'INT4',LENG:10},
      {FIELDNAME:'ADJUST_FLG',ROLLNAME:'ZE_ADJUST_FLG',DATATYPE:'CHAR',LENG:2},
      {FIELDNAME:'VERNUM',ROLLNAME:'ZE_VERNUM',DATATYPE:'CHAR',LENG:5},
      {FIELDNAME:'BUSTYPE',ROLLNAME:'ZE_BUSTYPE_1',DATATYPE:'CHAR',LENG:8},
      {FIELDNAME:'XREVERSAL',ROLLNAME:'XREVERSAL',DATATYPE:'CHAR',LENG:1},
      {FIELDNAME:'BLART',ROLLNAME:'BLART',DATATYPE:'CHAR',LENG:2},
      {FIELDNAME:'ZVOUTY',ROLLNAME:'ZE_VOUTY',DATATYPE:'CHAR',LENG:20},
      {FIELDNAME:'BKTXT',ROLLNAME:'BKTXT',DATATYPE:'CHAR',LENG:25},
      {FIELDNAME:'RACCT',ROLLNAME:'RACCT',DATATYPE:'CHAR',LENG:10},
      {FIELDNAME:'RACCT_TXT',ROLLNAME:'TXT50',DATATYPE:'CHAR',LENG:50},
      {FIELDNAME:'WAERS',ROLLNAME:'WAERS',DATATYPE:'CUKY',LENG:5},
      {FIELDNAME:'TSL',ROLLNAME:'VTCUR12',DATATYPE:'CURR',LENG:23,DECIMALS:2},
      {FIELDNAME:'HSL_S',ROLLNAME:'ZE_HSL_S',DATATYPE:'CURR',LENG:15,DECIMALS:2},
      {FIELDNAME:'HSL_H',ROLLNAME:'ZE_HSL_H',DATATYPE:'CURR',LENG:15,DECIMALS:2},
      {FIELDNAME:'KOSTL',ROLLNAME:'KOSTL',DATATYPE:'CHAR',LENG:10},
      {FIELDNAME:'KOSTL_TXT',ROLLNAME:'ZE_KOSTL_TXT',DATATYPE:'CHAR',LENG:40},
      {FIELDNAME:'PRCTR',ROLLNAME:'PRCTR',DATATYPE:'CHAR',LENG:10},
      {FIELDNAME:'PRCTR_TXT',ROLLNAME:'ZE_PRCTR_TXT',DATATYPE:'CHAR',LENG:40},
      {FIELDNAME:'SGTXT',ROLLNAME:'SGTXT',DATATYPE:'CHAR',LENG:50},
      {FIELDNAME:'MATNR',ROLLNAME:'MATNR',DATATYPE:'CHAR',LENG:18},
      {FIELDNAME:'MAKTX',ROLLNAME:'MAKTX',DATATYPE:'CHAR',LENG:40},
      {FIELDNAME:'KTOKD',ROLLNAME:'KTOKD',DATATYPE:'CHAR',LENG:4},
      {FIELDNAME:'KTOKD_TXT',ROLLNAME:'ZE_KTOKD_TXT',DATATYPE:'CHAR',LENG:30},
      {FIELDNAME:'ZYHZH',ROLLNAME:'ZE_YHZH',DATATYPE:'CHAR',LENG:50},
      {FIELDNAME:'ORGNAME',ROLLNAME:'ZE_ORGNAME',DATATYPE:'CHAR',LENG:40},
      {FIELDNAME:'MATKL',ROLLNAME:'MATKL',DATATYPE:'CHAR',LENG:9},
      {FIELDNAME:'WGBEZ60',ROLLNAME:'WGBEZ60',DATATYPE:'CHAR',LENG:60},
      {FIELDNAME:'LIFNR_FI',ROLLNAME:'ZE_LIFNR_FI',DATATYPE:'CHAR',LENG:10},
      {FIELDNAME:'NAME1_LIF_FI',ROLLNAME:'ZE_NAME1_LIF_FI',DATATYPE:'CHAR',LENG:35},
      {FIELDNAME:'KUNNR_FI',ROLLNAME:'ZE_KUNNR_FI',DATATYPE:'CHAR',LENG:10},
      {FIELDNAME:'NAME1_KUR_FI',ROLLNAME:'ZE_NAME1_KUR_FI',DATATYPE:'CHAR',LENG:35},
      {FIELDNAME:'HKONT_BKN',ROLLNAME:'ZE_HKONT_BKN',DATATYPE:'CHAR',LENG:50},
      {FIELDNAME:'HKONT_FDN',ROLLNAME:'ZE_HKONT_FDN',DATATYPE:'CHAR',LENG:50},
      {FIELDNAME:'KUNNR',ROLLNAME:'KUNNR',DATATYPE:'CHAR',LENG:10},
      {FIELDNAME:'NAME1_KUR',ROLLNAME:'ZE_NAME1_KUR',DATATYPE:'CHAR',LENG:40},
      {FIELDNAME:'LIFNR',ROLLNAME:'LIFNR',DATATYPE:'CHAR',LENG:10},
      {FIELDNAME:'NAME1_LIF',ROLLNAME:'ZE_NAME1_LIF',DATATYPE:'CHAR',LENG:40},
      {FIELDNAME:'EXPENSECODE',ROLLNAME:'ZE_EXPENSCODE',DATATYPE:'CHAR',LENG:20},
      {FIELDNAME:'EXPENSENAME',ROLLNAME:'ZE_EXPENSENAME',DATATYPE:'CHAR',LENG:50},
      {FIELDNAME:'ANLKL',ROLLNAME:'ANLKL',DATATYPE:'CHAR',LENG:8},
      {FIELDNAME:'NAME1_ANL',ROLLNAME:'ZE_NAME1_ANL',DATATYPE:'CHAR',LENG:50},
      {FIELDNAME:'LIFNR_PA',ROLLNAME:'ZE_LIFNR_PA',DATATYPE:'CHAR',LENG:10},
      {FIELDNAME:'NAME1_LIF_PA',ROLLNAME:'ZE_NAME1_LIF_PA',DATATYPE:'CHAR',LENG:40},
      {FIELDNAME:'MEINS',ROLLNAME:'MEINS',DATATYPE:'UNIT',LENG:3},
      {FIELDNAME:'PRICE',ROLLNAME:'ZE_PRICE',DATATYPE:'CURR',LENG:13,DECIMALS:2},
      {FIELDNAME:'MENGE',ROLLNAME:'MENGE_D',DATATYPE:'QUAN',LENG:13,DECIMALS:3},
      {FIELDNAME:'PAYMETHOD',ROLLNAME:'ZE_PAYMETHOD',DATATYPE:'CHAR',LENG:10},
      {FIELDNAME:'XBLNR',ROLLNAME:'XBLNR',DATATYPE:'CHAR',LENG:16},
      {FIELDNAME:'RAT_TYPE',ROLLNAME:'ZE_RAT_TYPE',DATATYPE:'CHAR',LENG:8},
      {FIELDNAME:'RAT',ROLLNAME:'ZE_RAT',DATATYPE:'CHAR',LENG:10},
      {FIELDNAME:'BUSNUM',ROLLNAME:'ZE_BUSNUM',DATATYPE:'CHAR',LENG:64},
      {FIELDNAME:'ABSLIB',ROLLNAME:'ZE_ABSLIB',DATATYPE:'CHAR',LENG:20},
      {FIELDNAME:'ZFKYH',ROLLNAME:'ZE_FKYH',DATATYPE:'CHAR',LENG:64},
      {FIELDNAME:'ACCTDIM',ROLLNAME:'ZE_ACCTDIM',DATATYPE:'CHAR',LENG:10}
    ]
  },
  'ZSAP_FI180': {
    tabname: 'ZSAP_FI180', source: 'DD03L',
    fields: [
      {FIELDNAME:'MANDT',KEYFLAG:'X',ROLLNAME:'MANDT',DATATYPE:'CLNT',LENG:3},
      {FIELDNAME:'BUKRS',KEYFLAG:'X',ROLLNAME:'BUKRS',DATATYPE:'CHAR',LENG:4},
      {FIELDNAME:'LTEXT',ROLLNAME:'LTEXT',DATATYPE:'CHAR',LENG:40},
      {FIELDNAME:'ZVOUTY',ROLLNAME:'ZE_VOUTY',DATATYPE:'CHAR',LENG:20}
    ]
  },
  'ZSAP_BUKRS': {
    tabname: 'ZSAP_BUKRS', source: 'DD03L',
    fields: [
      {FIELDNAME:'MANDT',KEYFLAG:'X',ROLLNAME:'MANDT',DATATYPE:'CLNT',LENG:3},
      {FIELDNAME:'BUKRS',KEYFLAG:'X',ROLLNAME:'ZE_BUKRS',DATATYPE:'CHAR',LENG:4},
      {FIELDNAME:'PRCTR',ROLLNAME:'PRCTR',DATATYPE:'CHAR',LENG:10},
      {FIELDNAME:'LTEXT',ROLLNAME:'LTEXT',DATATYPE:'CHAR',LENG:40},
      {FIELDNAME:'ZFGS',ROLLNAME:'ZE_FGSBS',DATATYPE:'CHAR',LENG:1},
      {FIELDNAME:'ZZGS',ROLLNAME:'BUKRS',DATATYPE:'CHAR',LENG:4},
      {FIELDNAME:'BUTXT',ROLLNAME:'BUTXT',DATATYPE:'CHAR',LENG:25},
      {FIELDNAME:'ZSYS',ROLLNAME:'ZE_SYS',DATATYPE:'CHAR',LENG:1}
    ]
  },
  'ZFI032_DOC': {
    tabname: 'ZFI032_DOC', source: 'DD03L',
    fields: [
      {FIELDNAME:'MANDT',KEYFLAG:'X',ROLLNAME:'MANDT',DATATYPE:'CLNT',LENG:3},
      {FIELDNAME:'URID',KEYFLAG:'X',ROLLNAME:'ZURID',DATATYPE:'CHAR',LENG:32},
      {FIELDNAME:'BANKSERIALNUMBER',KEYFLAG:'X',ROLLNAME:'',DATATYPE:'CHAR',LENG:64},
      {FIELDNAME:'BELNR',KEYFLAG:'X',ROLLNAME:'BELNR_D',DATATYPE:'CHAR',LENG:10},
      {FIELDNAME:'GJAHR',KEYFLAG:'X',ROLLNAME:'GJAHR',DATATYPE:'NUMC',LENG:4},
      {FIELDNAME:'BUKRS',KEYFLAG:'X',ROLLNAME:'BUKRS',DATATYPE:'CHAR',LENG:4},
      {FIELDNAME:'ZCXFLAG',KEYFLAG:'X',ROLLNAME:'ZCXFLAG',DATATYPE:'CHAR',LENG:1},
      {FIELDNAME:'OURBANKACCOUNTNUMBER',ROLLNAME:'',DATATYPE:'CHAR',LENG:64}
    ]
  },
  'ZSAP_FI054': {
    tabname: 'ZSAP_FI054', source: 'DD03L',
    fields: [
      {FIELDNAME:'MANDT',KEYFLAG:'X',ROLLNAME:'MANDT',DATATYPE:'CLNT',LENG:3},
      {FIELDNAME:'URID',KEYFLAG:'X',ROLLNAME:'ZURID',DATATYPE:'CHAR',LENG:32},
      {FIELDNAME:'BANKSERIALNUMBER',ROLLNAME:'',DATATYPE:'CHAR',LENG:64},
      {FIELDNAME:'BUKRS',ROLLNAME:'BUKRS',DATATYPE:'CHAR',LENG:4},
      {FIELDNAME:'BELNR',ROLLNAME:'BELNR_D',DATATYPE:'CHAR',LENG:10},
      {FIELDNAME:'GJAHR',ROLLNAME:'GJAHR',DATATYPE:'NUMC',LENG:4}
    ]
  }
};

for (const [name, data] of Object.entries(tables)) {
  fs.writeFileSync(path.join(d, `${name}.json`), JSON.stringify(data, null, 2));
  console.log(`${name}: ${data.fields.length} fields`);
}
console.log('All Z-table metadata written');
